apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- alertmanager.yaml
- podDisruptionBudget.yaml
- prometheusRule.yaml
- secret.yaml
- service.yaml
- serviceAccount.yaml
- serviceMonitor.yaml
