apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterRole.yaml
- clusterRoleBinding.yaml
- prometheus.yaml
- prometheusRule.yaml
- roleBindingConfig.yaml
- roleBindingSpecificNamespaces.yaml
- roleConfig.yaml
- roleSpecificNamespaces.yaml
- service.yaml
- serviceAccount.yaml
- serviceMonitor.yaml
- serviceMonitorApiserver.yaml
- serviceMonitorCoreDNS.yaml
- serviceMonitorKubeControllerManager.yaml
- serviceMonitorKubeScheduler.yaml
- serviceMonitorKubelet.yaml
